version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: turnos_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin1234!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./docker-init/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Admin1234!", "-Q", "SELECT 1", "-No"]
      interval: 15s
      timeout: 10s
      retries: 15
      start_period: 60s

  api:
    build: .
    container_name: turnos_api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: "Admin1234!"
      DB_NAME: turnos_db
      JWT_SECRET: "jwt_secret_demo_2024"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  frontend:
    build: ../demo-turnos-angular
    container_name: turnos_frontend
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  mssql_data:
